export default {
  // login: 'john-smilga',
  // id: 42133389,
  // node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  // avatar_url: 'https://avatars.githubusercontent.com/u/77687593?s=460&u=7c0796de369c94aa4f3c621cbac7879813875027&v=4',
  // gravatar_id: '',
  // url: 'https://api.github.com/users/shwetakamreddi',
  // html_url: 'https://github.com/john-smilga',
  // followers_url: 'https://api.github.com/users/john-smilga/followers',
  // following_url:
  //   'https://api.github.com/users/john-smilga/following{/other_user}',
  // gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  // starred_url:
  //   'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  // subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  // organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  // repos_url: 'https://api.github.com/users/john-smilga/repos',
  // events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  // received_events_url:
  //   'https://api.github.com/users/john-smilga/received_events',
  // type: 'User',
  // site_admin: false,
  // name: 'Shweta kamreddi',
  // company: 'Coding Addict',
  // blog: 'www.kamreddishweta.com',
  // location: 'Solapur',
  // email: null,
  // hireable: null,
  // bio: 'Learner|Developer',
  // twitter_username: 'john_smilga',
  // public_repos: 152,
  // public_gists: 0,
  // followers: 1495,
  // following: 0,
  // created_at: '2018-08-06T06:48:23Z',
  // updated_at: '2020-07-08T05:01:32Z',

  
    login: "shwetakamreddi",
    id: 77687593,
    node_id: "MDQ6VXNlcjc3Njg3NTkz",
    avatar_url: "https://avatars.githubusercontent.com/u/77687593?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/shwetakamreddi",
    html_url: "https://github.com/shwetakamreddi",
    followers_url: "https://api.github.com/users/shwetakamreddi/followers",
    following_url: "https://api.github.com/users/shwetakamreddi/following{/other_user}",
    "gists_url": "https://api.github.com/users/shwetakamreddi/gists{/gist_id}",
    starred_url: "https://api.github.com/users/shwetakamreddi/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/shwetakamreddi/subscriptions",
    organizations_url: "https://api.github.com/users/shwetakamreddi/orgs",
   repos_url: "https://api.github.com/users/shwetakamreddi/repos",
    events_url: "https://api.github.com/users/shwetakamreddi/events{/privacy}",
    received_events_url: "https://api.github.com/users/shwetakamreddi/received_events",
    type: "User",
    site_admin: false,
    name: "shweta kamreddi",
    company: "Fresher",
    blog: "",
    location : 'Solapur',
    email: null,
    hireable: null,
    bio: "Programmer|Developer|Learner|Reader",
    twitter_username: null,
    public_repos: 1,
    public_gists: 0,
    followers : 0,
    following: 0,
    created_at: "2021-01-19T16:40:29Z",
    updated_at: "2021-02-07T13:18:38Z"
  
};
